---
title: "Kobe Bryant EDA"
output: pdf_document
---


```{r}
library(devtools)
#install_github("rtelmore/ballr")
library(ballr)
library(tidyverse)
library(RColorBrewer)
library(forcats)
library(ggthemes)
library(viridis)
library(maps)
library(plotly)
```



```{r}
kobe <- read.csv("data.csv")
head(kobe)
```

```{r, warning=FALSE, message=FALSE}
source("Court.R")
kobe.filter <- kobe %>% 
    filter(shot_distance <= 30) %>%
    mutate(shot_zone_range = factor(shot_zone_range, 
                                    levels = c("Less Than 8 ft.", "8-16 ft.", "16-24 ft.", "24+ ft.")))
col_scheme <- c("firebrick4","darkorange2","gold1",
                "chartreuse4","dodgerblue", "darkorchid4")
ggplot() + geom_point(data = kobe.filter, aes(x = loc_x, y = loc_y + 52, color = shot_distance), size = .4) + geom_path(data = test.outer_key, aes(x= x, y = y)) + geom_path(data = test.perimeter, aes(x= x, y = y)) + geom_path(data = test.three, aes(x= x, y = y)) + ylim(-10, 350) +
    geom_path(data = test.backboard, aes(x= x, y = y)) +
    geom_path(data = test.neck, aes(x= x, y = y)) + 
    geom_path(data = test.hoop, aes(x= x, y = y)) + 
    geom_path(data = test.foul_circle, aes(x= x, y = y)) +
    geom_path(data = test.restricted, aes(x= x, y = y)) + 
    coord_fixed() + theme_void() + scale_color_gradientn(colors = col_scheme,limits = c(0,30), breaks = c(0, 30), name = 'Shot Distance (ft)') +
    labs(title = "Kobe Bryant Shot Distance")

ggplot() + geom_point(data = kobe.filter, aes(x = loc_x, y = loc_y + 52, color = shot_zone_range), size = .4) + geom_path(data = test.outer_key, aes(x= x, y = y)) + geom_path(data = test.perimeter, aes(x= x, y = y)) + geom_path(data = test.three, aes(x= x, y = y)) + ylim(-10, 350) +
    geom_path(data = test.backboard, aes(x= x, y = y)) +
    geom_path(data = test.neck, aes(x= x, y = y)) + 
    geom_path(data = test.hoop, aes(x= x, y = y)) + 
    geom_path(data = test.foul_circle, aes(x= x, y = y)) +
    geom_path(data = test.restricted, aes(x= x, y = y)) + 
    coord_fixed() + theme_void() + scale_color_manual(values = c("#D92027", "#FF9234", "#FFCD3C", "#35D0BA"), name = "Zone Range") + guides(colour = guide_legend(reverse = TRUE, override.aes = list(size = 5))) +
    labs(title = "Kobe Bryant Shot Zone Range")


ggplot() + geom_point(data = kobe.filter, aes(x = loc_x, y = loc_y + 52, color = shot_zone_area), size = .4) + geom_path(data = test.outer_key, aes(x= x, y = y)) + geom_path(data = test.perimeter, aes(x= x, y = y)) + geom_path(data = test.three, aes(x= x, y = y)) + ylim(-10, 350) +
    geom_path(data = test.backboard, aes(x= x, y = y)) +
    geom_path(data = test.neck, aes(x= x, y = y)) + 
    geom_path(data = test.hoop, aes(x= x, y = y)) + 
    geom_path(data = test.foul_circle, aes(x= x, y = y)) +
    geom_path(data = test.restricted, aes(x= x, y = y)) + 
    coord_fixed() + theme_void() + scale_color_manual(values = col_scheme, name = "Zone Range") + guides(colour = guide_legend(reverse = TRUE, override.aes = list(size = 5))) +
    labs(title = "Kobe Bryant Shot Zone Range")

```


```{r, warning=FALSE, message=FALSE}
shot.data <- kobe %>%
    filter(!is.na(shot_made_flag))

ggplot() + geom_point(data = shot.data, aes(x = loc_x, y = loc_y + 52, color = as.factor(shot_made_flag)), size = .75) + geom_path(data = test.outer_key, aes(x= x, y = y)) + geom_path(data = test.perimeter, aes(x= x, y = y)) + geom_path(data = test.three, aes(x= x, y = y)) + ylim(-10, 350) +
    geom_path(data = test.backboard, aes(x= x, y = y)) +
    geom_path(data = test.neck, aes(x= x, y = y)) + 
    geom_path(data = test.hoop, aes(x= x, y = y)) + 
    geom_path(data = test.foul_circle, aes(x= x, y = y)) +
    geom_path(data = test.restricted, aes(x= x, y = y)) + 
    coord_fixed() + theme_void() + scale_color_manual(values = c("#fdb927", "#552583"), labels = c("Miss", "Make"), name = "Zone Range") + guides(colour = guide_legend(reverse = TRUE, override.aes = list(size = 5))) +
    labs(title = "Kobe Bryant Shot Distance")

```


```{r, warning=FALSE, message=FALSE}
team_percentage <- shot.data %>% 
    group_by(opponent) %>%
    summarize(FGPercent = mean(shot_made_flag == 1),
              FG2Percent = sum(shot_made_flag == 1 & shot_type == "2PT Field Goal")/sum(shot_type == "2PT Field Goal"),
              FG3Percent = sum(shot_made_flag == 1 & shot_type == "3PT Field Goal")/sum(shot_type == "3PT Field Goal"))

team_games <- shot.data %>%
  group_by(opponent) %>%
  summarize(Games_Against = length(unique(game_id)))
team_percentage <- team_percentage %>% inner_join(team_games, by = "opponent")

team_percentage$conference <- c("East", "East", "East", "East", "East", "East", "West", "West", "East", "West", "West", "East", "West", "West", "East", "East", "West", "East", "West", "West", "East", "West", "East", "East", "West", "West", "West", "West", "West", "East", "West", "West", "East")
team_percentage$conference <- factor(team_percentage$conference)
team_percentage <- team_percentage %>% arrange(desc(FGPercent))

empty_bar <- 10
to_add <- data.frame( matrix(NA, empty_bar*nlevels(team_percentage$conference), ncol(team_percentage)) )
colnames(to_add) <- colnames(team_percentage)
to_add$conference <- rep(levels(team_percentage$conference), each=empty_bar)
team_percentage <- rbind(team_percentage, to_add)
team_percentage <- team_percentage %>% arrange(conference)
team_percentage$id <- seq(1, nrow(team_percentage))

label_data <- team_percentage
number_of_bar <- nrow(label_data)
angle <- 90 - 360 * (label_data$id-0.5) /number_of_bar     # I substract 0.5 because the letter must have the angle of the center of the bars. Not extreme right(1) or extreme left (0)
label_data$hjust <- ifelse( angle < -90, 1, 0)
label_data$angle <- ifelse(angle < -90, angle+180, angle)

base_data <- team_percentage %>% 
  group_by(conference) %>% 
  summarize(start=min(id), end=max(id) - empty_bar) %>% 
  rowwise() %>% 
  mutate(title=mean(c(start, end)))


grid_data <- base_data
grid_data$end <- grid_data$end[ c( nrow(grid_data), 1:nrow(grid_data)-1)] + 1
grid_data$start <- grid_data$start - 1
grid_data <- grid_data[-1,]

ggplot(team_percentage, aes(x=as.factor(id), y=FGPercent*100, fill=conference)) +       # Note that id is a factor. If x is numeric, there is some space between the first bar
  
  geom_bar(aes(x=as.factor(id), y=FGPercent*100, fill=conference), stat="identity", alpha=0.5) +
  
  # Add a val=100/75/50/25 lines. I do it at the beginning to make sur barplots are OVER it.
  geom_segment(data=grid_data, aes(x = end, y = 80, xend = start, yend = 80), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  geom_segment(data=grid_data, aes(x = end, y = 60, xend = start, yend = 60), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  geom_segment(data=grid_data, aes(x = end, y = 40, xend = start, yend = 40), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  geom_segment(data=grid_data, aes(x = end, y = 20, xend = start, yend = 20), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  
  # Add text showing the value of each 100/75/50/25 lines
  annotate("text", x = rep(max(team_percentage$id),4), y = c(20, 40, 60, 80), label = c("20", "40", "60", "80") , color="grey", size=3 , angle=0, fontface="bold", hjust=1) +
  
  geom_bar(aes(x=as.factor(id), y=FGPercent, fill=conference), stat="identity", alpha=0.5) +
   ylim(-50,100) + 
  theme_minimal() +
  theme(
    legend.position = "none",
    axis.text = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    plot.margin = unit(rep(-1,4), "cm") 
  ) +
  coord_polar() + 
  geom_text(data=label_data, aes(x=id, y=(FGPercent*100)+10, label=paste(opponent, " ",  round(FGPercent*100, digits = 2), "%", sep = ""), hjust=hjust), color="black", fontface="bold",alpha=0.6, size=2.5, angle= label_data$angle, inherit.aes = FALSE ) +
  # Add base line information
  geom_segment(data=base_data, aes(x = start, y = -5, xend = end, yend = -5), colour = "black", alpha=0.8, size=0.6 , inherit.aes = FALSE )  +
  geom_text(data=base_data, aes(x = title, y = -18, label=conference), hjust=c(1,0), colour = "black", alpha=0.8, size=4, fontface="bold", inherit.aes = FALSE) + labs(title ="Kobe Bryant Field Goal Percentage by Team") + scale_fill_manual(values = c("#0168ad", "#ed174b"))

```

```{r}
shot.type <- shot.data %>%
  group_by(action_type) %>%
  summarize(FGPercent = round(mean(shot_made_flag) * 100, digits = 2))
ggplot(shot.type, aes(fct_reorder(action_type, FGPercent), FGPercent)) +
  geom_bar(stat = "identity", fill = "#fdb927") + 
  geom_point(color = "#552583") +
  xlab("Shot type") +
  ylab("Field Goal Percentage") +
  coord_flip()

shot.type.small <- shot.data %>%
  group_by(combined_shot_type) %>%
  summarize(FGPercent = round(mean(shot_made_flag) * 100, digits = 2))

ggplot(shot.type.small, aes(fct_reorder(combined_shot_type, FGPercent), FGPercent)) +
  geom_bar(stat = "identity", fill = "#fdb927") + 
  geom_point(color = "#552583", size = 3) +
  xlab("Shot type") +
  ylab("Field Goal Percentage") +
  coord_flip() + theme_clean()
```


```{r}
arena <- read.csv("arenas.csv")
nba.arena <- arena %>% filter(leagueName == "National Basketball Association") %>% 
  select(teamName, venueName, lat, long)
extra_teams <- data.frame(teamName = c("Vancouver Grizzlies", "Seattle SuperSonics", "New Orleans Hornets", "New Jersey Nets"), venueName = c("Rogers Arena", "Key Arena", "Pete Maravich Assembly Center", "Continental Airlines Arena"), lat = c(49.277836, 47.6200, 30.4143, 40.8116), long = c(-123.108823, -122.3525, -91.1846, -74.0676))
nba.arena <- nba.arena %>% bind_rows(extra_teams) %>% 
  filter(teamName != "Los Angeles Lakers", teamName != "Indianapolis Olympians") %>%
  slice(c(1:2, 5:nrow(.))) %>%
  mutate(id = 1:33)

nba.arena$opponent <- c("ATL", "BOS", "BKN", "CHA", "CHI", "CLE", "DAL", "DEN", "DET", "GSW", "HOU", "IND", "LAC", "MEM", "MIA", "MIL", "MIN", "NOP", "NYK", "OKC", "ORL", "PHI", "PHX", "POR", "SAC", "SAS", "TOR", "UTA", "WAS", "VAN", "SEA", "NOH", "NJN")

teams <- team_percentage %>% inner_join(nba.arena, by = "opponent")
head(teams)

mybreaks <- c(.4, .415, .43, .445, .46, .475)
map <- map_data("world") %>% filter(region %in% c("Canada", "USA"))
teams <- teams %>%
  mutate(mytext = paste(teamName, "\n", venueName, "\n", "Conference: ", conference , "\n", "Games Against: ", Games_Against, "\n", "Field Goal Percentage: ", round(FGPercent*100, digits = 2), "%", sep = ""))
p <- ggplot() +
  geom_polygon(data = map, aes(x=long, y = lat, group = group), fill="grey", alpha=0.7) +
  geom_point( data=teams, aes(x=long, y=lat, color=FGPercent, size = FGPercent, text = mytext)) +
  scale_size_continuous(range=c(1,5), name = "Field Goal Percent", breaks = mybreaks) +
  scale_color_viridis(option = "viridis", name = "Field Goal Percent", breaks = mybreaks) +
  theme_void() +  coord_fixed(xlim = c(-135, -60),  ylim = c(20, 55), ratio = 1.2) + guides( colour = guide_legend()) + theme(legend.position = "bottom")

p.anim <- ggplotly(p, tooltip = "text")

p
p.anim

mytext_leaflet = paste(teams$teamName, "<br/>", teams$venueName, "<br/>", "Conference: ", teams$conference , "<br/>", "Games Against: ", teams$Games_Against, "<br/>", "Field Goal Percentage: ", round(teams$FGPercent*100, digits = 2), "%", sep = "") %>% lapply(htmltools::HTML)

library(leaflet)

mypalette <- colorBin(palette = "viridis", pretty = TRUE, domain = teams$FGPercent)

teams %>%
leaflet() %>%
  addProviderTiles("Esri") %>%
  addCircleMarkers(lng = ~long, lat = ~lat, label = mytext_leaflet,
                   color = ~mypalette(FGPercent), radius = 7, 
                   fillOpacity = 1, stroke = FALSE) %>%
  addLegend(pal = mypalette, values = ~FGPercent, opacity = .75, title = "Field Goal Percent", position = "bottomleft")

teams %>%
leaflet() %>%
  addProviderTiles("Esri") %>%
  addCircleMarkers(lng = ~long, lat = ~lat, label = mytext_leaflet,
                   color = ~mypalette(FGPercent), 
                   fillOpacity = 1, stroke = FALSE, radius = ~(Games_Against/5)) %>%
  addLegend(pal = mypalette, values = ~FGPercent, opacity = .75, title = "Field Goal Percent", position = "bottomleft")

```


```{r,warning=FALSE, message=FALSE}
library(ggridges)
library(hrbrthemes) 
ggplot(kobe.filter, aes(x = shot_distance, y = season, fill = ..x..)) +
  geom_density_ridges_gradient(scale = 2, rel_min_height = 0.01) +
  scale_fill_viridis(option = "C") +
  labs(title = 'Kobe Bryant Shot Distance by Season', y = "", x = "Shot distance (ft.)") +
  theme_ipsum() +
    theme(
      legend.position="none",
      panel.spacing = unit(0.1, "lines"),
      strip.text.x = element_text(size = 8)
    )

ggplot(kobe.filter, aes(x = shot_distance, y = as.factor(minutes_remaining), fill = ..x..)) +
  geom_density_ridges_gradient(scale = 3, rel_min_height = 0.01) +
  scale_fill_viridis(option = "inferno") +
  labs(title = 'Kobe Bryant Shot Distance by Minutes Remaining', y = "", x = "Shot distance (ft.)") +
  theme_ipsum() +
    theme(
      legend.position="none",
      panel.spacing = unit(0.1, "lines"),
      strip.text.x = element_text(size = 8)
    )

ggplot(kobe.filter, aes(x = shot_distance, y = shot_zone_area, fill = ..x..)) +
  geom_density_ridges_gradient(scale = 1.5, rel_min_height = 0.01) +
  scale_fill_viridis(option = "C") +
  labs(title = 'Kobe Bryant Shot Distance by Area', y = "", x = "Shot distance (ft.)") +
  theme_ipsum() +
    theme(
      legend.position="none",
      panel.spacing = unit(0.1, "lines"),
      strip.text.x = element_text(size = 8)
    )
```

```{r}
season.fg <- shot.data %>% 
  group_by(season) %>%
  summarize(FGPercent = round(mean(shot_made_flag), digits = 4),
            Percent2 = sum(shot_made_flag == 1 & shot_type == "2PT Field Goal")/sum(shot_type == "2PT Field Goal"),
              percent3 = sum(shot_made_flag == 1 & shot_type == "3PT Field Goal")/sum(shot_type == "3PT Field Goal")) 

library(hrbrthemes)
ggplot(season.fg, aes(x = season, y = FGPercent)) +
  geom_line(group = 1, color = "gray45") + 
  geom_point(shape=21, color="black", fill="darkmagenta", size=4) + 
  theme_fivethirtyeight() + scale_y_percent(limits = c(.33, .48)) + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + labs(title = "Kobe Bryant Field Goal Percentage Over Time")

playoffs <- shot.data %>% 
  filter(playoffs == 1) %>%
  group_by(season) %>%
  summarize(FGPercent = round(mean(shot_made_flag), digits = 4),
            Percent2 = sum(shot_made_flag == 1 & shot_type == "2PT Field Goal")/sum(shot_type == "2PT Field Goal"),
              percent3 = sum(shot_made_flag == 1 & shot_type == "3PT Field Goal")/sum(shot_type == "3PT Field Goal")) 

reg.season <- shot.data %>% 
  filter(playoffs == 0) %>%
  group_by(season) %>%
  summarize(FGPercent = round(mean(shot_made_flag), digits = 4),
            Percent2 = sum(shot_made_flag == 1 & shot_type == "2PT Field Goal")/sum(shot_type == "2PT Field Goal"),
              percent3 = sum(shot_made_flag == 1 & shot_type == "3PT Field Goal")/sum(shot_type == "3PT Field Goal"))

ggplot(season.fg, aes(x = season, group = 1)) +
  geom_line(data = playoffs, aes(color = "Play", y = FGPercent)) + 
  geom_line(data = reg.season, aes(color = "Season", y = FGPercent)) + 
  geom_point(data = playoffs, aes(color = "Play", y = FGPercent), size = 3) + 
  geom_point(data = reg.season, aes(color = "Season", y = FGPercent), size = 3) +
  scale_y_percent(limits = c(.33, .52)) + theme_bw() + theme(axis.text.x = element_text(angle = 45, hjust = 1), legend.position = "bottom", panel.grid.major.x = element_blank(), panel.grid.major.y = element_line(linetype = "dashed")) + scale_color_manual(name ="", values = c("#195190FF", "#A2A2A1FF"), labels = c("Playoffs", "Regular Season")) + labs(x = "", y = "Percent", title = "Kobe Bryant Field Goal Percentage", subtitle = "Regular Season vs. Playoffs")
  
  geom_point(shape=21, color="black", fill="darkmagenta", size=4) + 
  theme_fivethirtyeight() + scale_y_percent(limits = c(.30, .48)) + theme(axis.text.x = element_text(angle = 45)) + labs(title = "Kobe Bryant Field Goal Percentage Over Time")
```

```{r}
library(hexbin)
ggplot(shotDataf, aes(x=LOC_X, y=LOC_Y)) + 
    annotation_custom(court, -250, 250, -52, 418) +
    stat_binhex(bins = 25, colour = "gray", alpha = 0.7) +
    scale_fill_gradientn(colours = c("yellow","orange","red")) +
    guides(alpha = FALSE, size = FALSE) +
    xlim(250, -250) +
    ylim(-52, 418) +
    geom_rug(alpha = 0.2) +
    coord_fixed() +
    ggtitle(paste("Shot Chart\n", unique(shotDataf$PLAYER_NAME), sep = "")) +
    theme(line = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        legend.title = element_blank(),
        plot.title = element_text(size = 17, lineheight = 1.2, face = "bold"))
     

ggplot()  + geom_path(data = test.outer_key, aes(x= x, y = y)) + geom_path(data = test.perimeter, aes(x= x, y = y)) + geom_path(data = test.three, aes(x= x, y = y)) + ylim(-10, 350) +
    geom_path(data = test.backboard, aes(x= x, y = y)) +
    geom_path(data = test.neck, aes(x= x, y = y)) + 
    geom_path(data = test.hoop, aes(x= x, y = y)) + 
    geom_path(data = test.foul_circle, aes(x= x, y = y)) +
    geom_path(data = test.restricted, aes(x= x, y = y)) + 
    stat_binhex(data = kobe.filter, aes(x = loc_x, y = loc_y + 52), bins = 10, colour = "gray", alpha = 0.7) + 
    scale_fill_gradientn(colours = c("yellow","orange","red")) +
    guides(alpha = FALSE, size = FALSE) +
    coord_fixed() + theme_void() + scale_color_gradientn(colors = col_scheme,limits = c(0,30), breaks = c(0, 30), name = 'Shot Distance (ft)') +
    labs(title = "Kobe Bryant Shot Distance")
head(kobe)
```

